/*
 * Td7 du cours d'ALG2G.
 */
package nap.soft.project.additionneur.vue;

import nap.soft.project.additionneur.architecturemvc.AdditionneurModele;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 * Représente la vue additionneur statique.
 *
 * @author g35991(Tuncer Can.)
 */
public class AdditionneurVueStatique extends AbstractAdditionneurVue {

    /**
     * Permet de créer un nouveau AdditionneurStatique.
     */
    public AdditionneurVueStatique() {
        initComponents();
    }

    /**
     * Permet de créer un nouveau AdditionneurStatique.
     *
     * @param aModele le modèle
     */
    public AdditionneurVueStatique(AdditionneurModele aModele) {
        initComponents();
        setModele(aModele);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monNombreStatique1 = new nap.soft.project.additionneur.vue.outils.MonNombreStatique();
        btRafraîchir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 200));

        btRafraîchir.setText("Rafraîchir");
        btRafraîchir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRafraîchirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(monNombreStatique1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(btRafraîchir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(monNombreStatique1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRafraîchir)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btRafraîchirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRafraîchirActionPerformed
        monNombreStatique1.setNombre(getModele().getListeners());
    }//GEN-LAST:event_btRafraîchirActionPerformed

    /**
     * Permet de définir les nouvelles etats des termes.
     */
    @Override
    public void notifieChangement() {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRafraîchir;
    private nap.soft.project.additionneur.vue.outils.MonNombreStatique monNombreStatique1;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        JFrame jf = new JFrame();
        jf.add(new AdditionneurVueStatique(), BorderLayout.CENTER);
        jf.pack();
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);

    }
}
