/**
 * Td7 du cours d'ALG2G.
 */
package nap.soft.project.additionneur.vue;

import nap.soft.project.additionneur.architecturemvc.AdditionneurModele;
import nap.soft.project.additionneur.architecturemvc.Etat;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *Représente la vue additionneur vue simple binaire.
 * @author  g35991(Tuncer Can.)
 */
public class AdditionneurVueSimpleBinaire extends AbstractAdditionneurVue {

    /** Creates new form AdditionneurVueSimple */
    public AdditionneurVueSimpleBinaire() {
        initComponents();
        monNombreBinaire1.setNbLed(17);
        monNombreBinaire2.setNbLed(17);
        monNombreBinaire3.setNbLed(18);
    }

     /** Creates new form AdditionneurVueSimple */
    public AdditionneurVueSimpleBinaire(AdditionneurModele aModele) {
        initComponents();
        setModele(aModele);
        monNombreBinaire1.setNbLed(17);
        monNombreBinaire2.setNbLed(17);
        monNombreBinaire3.setNbLed(18);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            monNombreBinaire1 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaire();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        try {
            monNombreBinaire2 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaire();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel6 = new javax.swing.JLabel();
        try {
            monNombreBinaire3 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaire();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 300));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));
        add(monNombreBinaire1);

        jLabel1.setText("      ");
        add(jLabel1);
        add(monNombreBinaire2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" +");
        add(jLabel6);
        add(monNombreBinaire3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("=  ");
        add(jLabel7);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void notifieChangement() {
       Etat e =  getModele().getEtat() ;  
       monNombreBinaire1.setNombre(e.getTerme1());
       monNombreBinaire2.setNombre(e.getTerme2());
       monNombreBinaire3.setNombre(e.getSomme());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaire monNombreBinaire1;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaire monNombreBinaire2;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaire monNombreBinaire3;
    // End of variables declaration//GEN-END:variables

    public static void main (String[] args) {
        JFrame jf =  new JFrame() ; 
        jf.add(new AdditionneurVueSimpleBinaire(), BorderLayout.CENTER) ; 
        jf.pack() ; 
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);
              
    }
}
