/**
 * Td7 du cours d'ALG2G.
 */
package nap.soft.project.additionneur.vue;

import nap.soft.project.additionneur.architecturemvc.AdditionneurModele;
import nap.soft.project.additionneur.architecturemvc.AdditionneurOverflowException;
import nap.soft.project.additionneur.architecturemvc.Etat;
import nap.soft.project.additionneur.architecturemvc.Termes;
import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JFrame;

/**
 *Représente la vue additionneur vue saisie binaire.
 * @author  g35991(Tuncer Can.)
 */
public class AdditionneurVueSaisieBinaire extends AbstractAdditionneurVue {

    /** 
     * Permet de créer un nouveau addionneurVueSaisieBinaire
     */
    public AdditionneurVueSaisieBinaire() {
        initComponents();
        monNombreBinaireSaisie1.setNbLed(17);
        monNombreBinaireSaisie2.setNbLed(17);
        monNombreBinaireSaisie3.setNbLed(18);
        monNombreBinaireSaisie3.setClickable(false);    
    }
    

     /** 
      * Permet de créer un nouveau AdditionneurVueSaisieBinaire 
      * @param aModele l'additionneurModele.
      */
    public AdditionneurVueSaisieBinaire(AdditionneurModele aModele) {
        initComponents();
        setModele(aModele);
        monNombreBinaireSaisie1.setNbLed(17);
        monNombreBinaireSaisie2.setNbLed(17);
        monNombreBinaireSaisie3.setNbLed(18);
        monNombreBinaireSaisie3.setClickable(false);
    
        PropertyChangeListener ecouteur = new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals("chgEtatLed")) {
                    try {
                        getModele().calcule(new Termes(monNombreBinaireSaisie1.getAffichBin().getValeurTmp(), monNombreBinaireSaisie2.getAffichBin().getValeurTmp()));
                        
                    } catch (AdditionneurOverflowException ex) {      
                    }
                }
            }
        };
        monNombreBinaireSaisie1.getAffichBin().addPropertyChangeListener(ecouteur);
        monNombreBinaireSaisie2.getAffichBin().addPropertyChangeListener(ecouteur);
                
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            monNombreBinaireSaisie1 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        try {
            monNombreBinaireSaisie2 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel6 = new javax.swing.JLabel();
        try {
            monNombreBinaireSaisie3 = new nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie();
        } catch (be.esi.alg.td5.AfficheurBinaireException e1) {
            e1.printStackTrace();
        }
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 300));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));
        add(monNombreBinaireSaisie1);

        jLabel1.setText("      ");
        add(jLabel1);
        add(monNombreBinaireSaisie2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(" +");
        add(jLabel6);
        add(monNombreBinaireSaisie3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("=  ");
        add(jLabel7);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void notifieChangement() {
       Etat e =  getModele().getEtat() ;  
       monNombreBinaireSaisie1.setNombre(e.getTerme1());
       monNombreBinaireSaisie2.setNombre(e.getTerme2());
       monNombreBinaireSaisie3.setNombre(e.getSomme());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie monNombreBinaireSaisie1;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie monNombreBinaireSaisie2;
    private nap.soft.project.additionneur.vue.outils.MonNombreBinaireSaisie monNombreBinaireSaisie3;
    // End of variables declaration//GEN-END:variables

    public static void main (String[] args) {
        JFrame jf =  new JFrame() ; 
        jf.add(new AdditionneurVueSaisieBinaire(), BorderLayout.CENTER) ; 
        jf.pack() ; 
        jf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        jf.setVisible(true);
              
    }
}
