/**
 * Td7 du cours d'ALG2G.
 */
package nap.soft.project.additionneur.vue.outils;

import java.awt.Color;
import javax.swing.UIManager;

/**
 *  Présentation d'un nombre romain.
 */
public class MonNombreRomain extends javax.swing.JPanel {

    /**
     * Creates new form MonNombreDecimal
     */
    public MonNombreRomain() {
        initComponents();
    }

    /**
     * assigne la valeur fournie au nombre
     */
    public void setNombre(int i) {
            if (i < 10000) {
                jLabel1.setText(numberToRoman(i));
                Color couleurParDefaut = UIManager.getColor("Panel.background");
                jPanel1.setBackground(couleurParDefaut);
            } else {
                jPanel1.setBackground(Color.RED);
                if (jPanel1.getBackground() == Color.RED) {
                }
            }
    }


    
    
    static String numberToRoman(int X) {
       String S;
       S = "";
       
       switch((X % 10000) / 1000) {
       case 9: S+="MMMMMMMMM";break;
       case 8: S+="MMMMMMMM";break;
       case 7: S+="MMMMMMM";break;
       case 6: S+="MMMMMM";break;
       case 5: S+="MMMMMM";break;
       case 4: S+="MMMMM";break;
       case 3: S+="MMMM";break;
       case 2: S+="MM";break;
       case 1: S+="M";break;
      }
      switch((X % 1000) / 100) {
       case 9: S+="CM";break;
       case 8: S+="DCCC";break;
       case 7: S+="DCC";break;
       case 6: S+="DC";break;
       case 5: S+="D";break;
       case 4: S+="CD";break;
       case 3: S+="CCC";break;
       case 2: S+="CC";break;
       case 1: S+="C";break;
      }
      switch((X % 100) / 10) {
       case 9: S+="XC";break;
       case 8: S+="LXXX";break;
       case 7: S+="LXX";break;
       case 6: S+="LX";break;
       case 5: S+="L";break;
       case 4: S+="XL";break;
       case 3: S+="XXX";break;
       case 2: S+="XX";break;
       case 1: S+="X";break;
      }
      switch(X % 10) {
       case 9: S+="IX";break;
       case 8: S+="VIII";break;
       case 7: S+="VII";break;
       case 6: S+="VI";break;
       case 5: S+="V";break;
       case 4: S+="IV";break;
       case 3: S+="III";break;
       case 2: S+="II";break;
       case 1: S+="I";break;
      }
      return S;
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("111111111111");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
