/**
 * Td7 du cours d'ALG2G.
 */
package nap.soft.project.additionneur.vue.outils;

import be.esi.alg.td5.AfficheurBinaire;
import be.esi.alg.td5.AfficheurBinaireException;
import be.esi.alg.td5.AfficheurBinaireOverflowException;
import java.util.logging.Level;
import java.util.logging.Logger;



/**
 * Présentation d'un nombre binaire.
 * @author g35991(Tuncer Can.).
 */
public class MonNombreBinaireSaisie extends javax.swing.JPanel {

    /**
     * Creates new form MonNombreDecimal
     */
    public MonNombreBinaireSaisie()throws AfficheurBinaireException{
        initComponents();
        afficheurBinaire1.addPropertyChangeListener(afficheurBinaire1);
    }
    
    /**
     * 
     * @return 
     */
    public AfficheurBinaire getAffichBin(){
        return afficheurBinaire1;
    }

    /**
     * assigne la valeur fournie au nombre
     */
    public void setNombre(int i){   
        try {
            afficheurBinaire1.setValue(i);
        } catch (AfficheurBinaireOverflowException ex) {
            Logger.getLogger(MonNombreBinaireSaisie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void setNbLed(int i){
        try{
            afficheurBinaire1.setNbLeds(i);
        }catch(AfficheurBinaireException ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void setClickable(boolean clickable){
            afficheurBinaire1.setClickable(clickable);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afficheurBinaire1 = new be.esi.alg.td5.AfficheurBinaire();

        setLayout(new java.awt.BorderLayout());
        add(afficheurBinaire1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private be.esi.alg.td5.AfficheurBinaire afficheurBinaire1;
    // End of variables declaration//GEN-END:variables

}
