/**
 *Td7 du cours d'ALG2G.
 */

package nap.soft.project.additionneur.vue.outils;

/**
 *  Présentation d'un nombre décimal
 */
public class MonNombreDecimal extends javax.swing.JPanel {

    /**
     * Creates new form MonNombreDecimal
     */
    public MonNombreDecimal() {
        initComponents();
    }

    /**
     * assigne la valeur fournie au nombre
     */
    public void setNombre(int i){
        jLabel1.setText(""+i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("111111111111");
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
