/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nap.soft.project.additionneur.vue.outils;

/**
 * Slider présentatnt la valeur sélectionnée
 */
public class MonSlider extends javax.swing.JPanel {

    /**
     * Message du PropertyChangeEvent &eacute;mis lors de la modification de la valeur du slider
     */
    public static final String VALUE_CHANGED="VALUE_CHANGED";
    private int value;
    /**
     * Creates new form MonSlider
     */
    public MonSlider() {
        initComponents();
        jSlider1.setValue(0);
        raffraichitValeur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLaffValeur = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(450, 40));
        setPreferredSize(new java.awt.Dimension(500, 40));

        jSlider1.setMajorTickSpacing(10000);
        jSlider1.setMaximum(100000);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.setMaximumSize(new java.awt.Dimension(1000, 31));
        jSlider1.setMinimumSize(new java.awt.Dimension(300, 31));
        jSlider1.setPreferredSize(new java.awt.Dimension(400, 31));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        add(jSlider1);

        jLaffValeur.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLaffValeur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLaffValeur.setText("jLabel1");
        jLaffValeur.setMaximumSize(new java.awt.Dimension(140, 15));
        jLaffValeur.setMinimumSize(new java.awt.Dimension(120, 15));
        jLaffValeur.setPreferredSize(new java.awt.Dimension(120, 15));
        add(jLaffValeur);
    }// </editor-fold>//GEN-END:initComponents

    
    private void raffraichitValeur(){
        int oldValue=value;
        value=jSlider1.getValue();
        jLaffValeur.setText(""+value);
        value=jSlider1.getValue();
        firePropertyChange(VALUE_CHANGED, oldValue, value);
    }
    
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        raffraichitValeur();
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * retourne la valeur du slider
     * @return 
     */
    public int getValue(){
        return value;
    }
    
    public void setValue(int val){
        this.jSlider1.setValue(val);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLaffValeur;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables
}
